from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    # path('', Sphera.as_view(), name='home'),
    # path('', ShowNews.as_view(), name='home'),
    path('', main_page, name='home'),
    path('show_post/<slug:post_slug>', ShowPost.as_view(), name='show_post'),
    path('category/<slug:cat_slug>/', ShowCategories.as_view(), name='category'),
    path('company.json', JsonCategories.as_view(), name='company_json'),
    path('add_post/', AddPost.as_view(), name='add_post'),
    path('update_post/<slug:slug>', UpdatePost.as_view(), name='update_post'),
    path('delete_post/<slug:slug>', DeletePost.as_view(), name='delete_post'),
    path('search_venues/', search_venues, name='search-venues'),
    path('user_registration/', CustomUserRegistration.as_view(), name='user_registration'),
    path('login/', CustomUserAuthentication.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('show_venues/', ShowVenues.as_view(), name='show_venues'),
    path('show_news/', ShowNews.as_view(), name='show_news'),
    path('add_review/', AddReview.as_view(), name='add_review'),

    path('add_new/', AddNews.as_view(), name='add_new'),
    path('delete_new/<slug:slug>', DeleteNews.as_view(), name='delete_new'),
    path('show_new/<slug:new_slug>', ShowNew.as_view(), name='show_new'),
    path('update_new/<slug:slug>', UpdateNews.as_view(), name='update_new'),
    path('create_profile/', CreateProfile.as_view(), name = 'create_profile'),
    path('show_profile/<int:pk>/', ShowProfile.as_view(), name ='profile'),
    path('delete_profile/<int:pk>/', DeleteProfile.as_view(), name= 'delete_profile'),
    path('update_profile/<int:pk>/', UpdateProfile.as_view(), name = 'update_profile'),
    path('add_comment/<int:pk>/', AddCommentView.as_view(), name='add_comment'),
    path('delete_comment/<int:pk>/del_comment/', DeleteCommentView.as_view(), name='delete_comment'),
    path('add_news_comment/<int:pk>/', AddNewsCommentView.as_view(), name='add_news_comment'),
    path('delete_news_comment/<int:pk>/del_comment/', DeleteNewsCommentView.as_view(), name='delete_news_comment'),
    # path('like/<slug:slug>', likeview, name='like_post'),
    path('fav/<slug:slug>', favview, name='fav_post'),
    # path('show_post/<slug:slug>', favview, name='fav_post'),
    path('favourites/',show_fav,  name='show_fav'),
    path("password_reset/", views.PasswordResetView.as_view(template_name='sforum/registration/password_reset_form.html'), name="password_reset"),
    path("password_reset/done/", views.PasswordResetDoneView.as_view(template_name='sforum/registration/password_reset_done.html'),name="password_reset_done"),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('agreement/', agreement, name='agreement'),
    path('in_process/', in_process, name='in_process'),
    path('add_banner_photo/', AddBannerPhotoView.as_view(), name='add_banner_photo'),
    path('delete_banner_photo/<int:pk>', DeleteBannerPhotoView.as_view(), name='delete_banner_photo'),
    path('add_banner_video/', AddBannerVideoView.as_view(), name='add_banner_video'),
    path('delete_banner_video/<int:pk>', DeleteBannerVideoView.as_view(), name='delete_banner_video'),
    path('show_reviews/', ShowReviews.as_view(), name='show_reviews'),
]
