[program:sfera]
command=/home/andrey/venv/bin/gunicorn sphera.wsgi:application -c /home/andrey/sfera_production/sphera/config/gunicorn.conf.py
directory=/home/andrey/sfera_production/sphera/sphera
user=andrey
autorestart=true
redirect_stderr=true
stdout_logfile = /home/andrey/sfera_production/sphera/logs/debug.log



