[program:sfera]
command=/home/andrey/venv/bin/gunicorn sphera.sphera.wsgi:application -c /home/john/sphera/config/gunicorn.conf.py
directory=/home/andrey/sphera
user=andrey
autorestart=true
redirect_stderr=true
stdout_logfile = /home/john/sphera/logs/debug.log