# Generated by Django 4.2.2 on 2024-10-07 10:26

import autoslug.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BannerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/main_banner_photos/%Y/%m/%d/', verbose_name='Баннер главный')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/main_banner_videos/%Y/%m/%d/', verbose_name='Баннер главный')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='photos/news/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='photos/reviews/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='photos/profile_images/%Y/%m/%d/', verbose_name='Фото профиля')),
                ('tg_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграмм')),
                ('vk_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВК')),
                ('web_site_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инстаграмм')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Имя профиля')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='sforum.companynews', verbose_name='Обсуждение')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Aдрес')),
                ('metro', models.CharField(choices=[('Академическая', 'Академическая'), ('Александровский сад', 'Александровский сад'), ('Алтуфьево', 'Алтуфьево'), ('Арбатская', 'Арбатская'), ('Баррикадная', 'Баррикадная'), ('Белорусская', 'Белорусская'), ('Библиотека имени Ленина', 'Библиотека имени Ленина'), ('Борисово', 'Борисово'), ('Ботанический сад', 'Ботанический сад'), ('Варшавская', 'Варшавская'), ('ВДНХ', 'ВДНХ'), ('Владыкино', 'Владыкино'), ('Волжская', 'Волжская'), ('Воробьёвы горы', 'Воробьёвы горы'), ('Деловой центр', 'Деловой центр'), ('Дмитровская', 'Дмитровская'), ('Дубровка', 'Дубровка'), ('Европейская', 'Европейская'), ('Жулебино', 'Жулебино'), ('Зеленоградская', 'Зеленоградская'), ('Зябликово', 'Зябликово'), ('Калужская', 'Калужская'), ('Киевская', 'Киевская'), ('Китай-город', 'Китай-город'), ('Киностудия имени Горького', 'Киностудия имени Горького'), ('Кожуховская', 'Кожуховская'), ('Коломенская', 'Коломенская'), ('Коньково', 'Коньково'), ('Краснопресненская', 'Краснопресненская'), ('Краснополянская', 'Краснополянская'), ('Кубинка', 'Кубинка'), ('Кузнецкий мост', 'Кузнецкий мост'), ('Кутузовская', 'Кутузовская'), ('Ленинский проспект', 'Ленинский проспект'), ('Лубянка', 'Лубянка'), ('Маяковская', 'Маяковская'), ('Медведково', 'Медведково'), ('Москва-сити', 'Москва-сити'), ('Митино', 'Митино'), ('Мытищи', 'Мытищи'), ('Нагорная', 'Нагорная'), ('Нагатинская', 'Нагатинская'), ('Наливная', 'Наливная'), ('Нижегородская', 'Нижегородская'), ('Новогиреево', 'Новогиреево'), ('Новокосино', 'Новокосино'), ('Новоясеневская', 'Новоясеневская'), ('Октябрьская', 'Октябрьская'), ('Озерная', 'Озерная'), ('Орехово', 'Орехово'), ('Павелецкая', 'Павелецкая'), ('Панфиловская', 'Панфиловская'), ('Печерская', 'Печерская'), ('Планерная', 'Планерная'), ('Площадь Революции', 'Площадь Революции'), ('Пушкинская', 'Пушкинская'), ('Раменки', 'Раменки'), ('Рижская', 'Рижская'), ('Румянцево', 'Румянцево'), ('Савеловская', 'Савеловская'), ('Семеновская', 'Семеновская'), ('Серпуховская', 'Серпуховская'), ('Скобелевская', 'Скобелевская'), ('Славянский бульвар', 'Славянский бульвар'), ('Смоленская', 'Смоленская'), ('Сокол', 'Сокол'), ('Старокачаловская', 'Старокачаловская'), ('Студенческая', 'Студенческая'), ('Таганская', 'Таганская'), ('Тверская', 'Тверская'), ('Тимирязевская', 'Тимирязевская'), ('Тульская', 'Тульская'), ('Улица 1905 года', 'Улица 1905 года'), ('Удальцова', 'Удальцова'), ('Ульяновская', 'Ульяновская'), ('Фрунзенская', 'Фрунзенская'), ('Хорошёво', 'Хорошёво'), ('ЦДК', 'ЦДК'), ('Черкизовская', 'Черкизовская'), ('Чистые пруды', 'Чистые пруды'), ('Шаболовская', 'Шаболовская'), ('Шелепиха', 'Шелепиха'), ('Щелковская', 'Щелковская'), ('Электрозаводская', 'Электрозаводская'), ('Юго-Западная', 'Юго-Западная'), ('Южная', 'Южная'), ('Ясенево', 'Ясенево'), ('Киевская', 'Киевская'), ('Кунцевская', 'Кунцевская'), ('Славянский бульвар', 'Славянский бульвар'), ('Студенческая', 'Студенческая'), ('Шелепиха', 'Шелепиха'), ('Лужники', 'Лужники'), ('Кропоткинская', 'Кропоткинская'), ('Краснопресненская', 'Краснопресненская'), ('Звенигородская', 'Звенигородская'), ('Каширская', 'Каширская'), ('Таганская', 'Таганская'), ('Нагорная', 'Нагорная'), ('Фрунзенская', 'Фрунзенская')], max_length=255, verbose_name='Станция метро')),
                ('latitude', models.FloatField(db_index=True, max_length=255, verbose_name='Широта')),
                ('longitude', models.FloatField(db_index=True, max_length=255, verbose_name='Долгота')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Ссылка')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('photo', models.ImageField(upload_to='photos/posts/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sforum.categories', verbose_name='Категория')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Название компании')),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sforum.companypost', verbose_name='Обсуждение')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
        ),
    ]
