# Generated by Django 4.2.2 on 2025-02-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sforum', '0002_bannerlink_bannerphoto_title_bannervideo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_options',
            field=models.CharField(choices=[('FIRE_FUN', 'FIRE_FUN'), ('FOR_LIFE', 'FOR_LIFE')], max_length=255, null=True, verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='bannerlink',
            name='body_link',
            field=models.TextField(db_index=True, null=True, verbose_name='Ссылка на партнеров'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='photo',
            field=models.ImageField(upload_to='photos/news/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='companypost',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон в формате +7'),
        ),
    ]
