# Generated by Django 4.2.2 on 2025-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sforum', '0003_profile_profile_options_alter_bannerlink_body_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_options',
            field=models.CharField(blank=True, choices=[('FIRE_FUN', 'FIRE_FUN'), ('FOR_LIFE', 'FOR_LIFE')], max_length=255, null=True, verbose_name='Опции'),
        ),
    ]
